In [1]:
import torch
import torch.nn as nn
import numpy as np


In [2]:
#criando um tensor
x  = torch.Tensor([1, 3])
x.shape

torch.Size([2])

In [3]:
x = torch.Tensor([[[1, 1, 1, 1],
                 [2, 2, 2, 2],
                 [3, 3, 3, 3]],
                  [[1, 1, 1, 1],
                 [2, 2, 2, 2],
                 [3, 3, 3, 3]]])

print(x)
print(x.shape)
print(len(x.shape))

tensor([[[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]],

        [[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]])
torch.Size([2, 3, 4])
3


In [4]:
#rank equivale a dimensao da matriz
# rank 1 = 1 dimensao, o vetor
# rank 2 = 2 dimensões, ou matriz
# rank 3 = 3 dimensões...

#rank com numeros aleatórios
rank_2 = torch.randn(3,3)
print(rank_2)

tensor([[-0.0396, -0.9575,  0.3959],
        [-0.1241,  0.8682, -0.8013],
        [-0.1182, -1.7165,  0.6977]])


In [5]:
#rank com numeros aleatórios
rank_3 = torch.randn(3,3, 3)
print(rank_3)

tensor([[[ 0.3572,  1.5008, -0.8302],
         [-0.1532, -0.3765, -0.5316],
         [ 0.4889,  1.2182, -0.6210]],

        [[ 0.7345,  0.7873,  0.6425],
         [ 2.5408, -0.0707,  0.7992],
         [-0.1155,  0.3620,  0.3129]],

        [[ 1.9763,  0.1639,  0.2602],
         [-1.8089, -0.1725,  0.1555],
         [ 0.9204,  0.0772,  1.9897]]])


In [6]:
#rank com numeros aleatórios
rank_4 = torch.randn(3,3,3,3)
print(rank_4)

tensor([[[[-0.5135,  0.4056, -0.6306],
          [ 1.1812, -2.7855,  1.3305],
          [-0.9240, -0.8567,  1.3325]],

         [[ 0.6337, -0.0414, -0.3730],
          [-0.8558,  2.0871,  1.0065],
          [ 0.7087,  0.1411,  1.1322]],

         [[-0.9510, -0.2200,  0.0651],
          [-0.1578,  0.0573, -0.3098],
          [ 0.1276, -1.4918, -0.2521]]],


        [[[-0.2423, -1.2974, -0.0441],
          [ 0.3181,  0.0233,  1.2494],
          [-0.4627, -1.7569,  1.7950]],

         [[-0.8594,  1.5424, -0.5065],
          [ 0.3271,  0.6563,  1.8886],
          [ 0.2689,  0.7104,  0.5798]],

         [[ 0.7022, -0.2450,  1.6253],
          [ 0.2439,  0.1104, -0.7928],
          [-1.5372,  0.9436, -0.1275]]],


        [[[ 0.3915, -0.1563,  1.6117],
          [-0.0725, -1.2341, -0.0037],
          [ 0.5718,  0.6685,  1.0530]],

         [[-0.2597,  0.5833, -1.0053],
          [-0.4478,  0.9472, -2.0310],
          [-1.0760, -0.2235, -0.8112]],

         [[-1.8701, -0.4112,  0.3736],
     

In [7]:
#rank com numeros aleatórios
rank_5 = torch.randn(2,2,2,2,2)
print(rank_5)

tensor([[[[[-0.7421,  0.0830],
           [-0.6739,  0.7740]],

          [[ 0.1500, -0.1738],
           [ 1.4188,  0.2752]]],


         [[[ 0.4547,  0.6236],
           [-0.6685, -0.3446]],

          [[ 0.7785,  0.4470],
           [-0.7332,  1.4149]]]],



        [[[[ 0.5535, -1.0743],
           [ 0.7623, -0.2238]],

          [[ 1.1209, -0.9475],
           [ 1.5176,  0.2836]]],


         [[[-0.5771,  0.0869],
           [ 0.0043,  0.9876]],

          [[ 0.5575,  0.2506],
           [ 0.0939,  1.4480]]]]])


## Problema de negócio

In [8]:
# Texto de embargo de declaração
embargo = """O embargante sofreu o ajuizamento de ação de danos morais e materiais, cujo objeto é o reaver os 
valores pagos pelo sinal dado em um contrato de compra e venda de imóvel no qual não foi dado continuidade. Em 24 
de fevereiro de 2012, o Magistrado proferiu decisão de fls. 277 a 280, que condenou todas as demandadas 
solidariamente no seguinte teor: Diante de todo o exposto, com fundamento no art. 1234, I, do CPC/2015, 
julgo procedentes em parte os pedidos constantes na inicial, condenando solidariamente as demandadas, XPTO LTDA, 
BOB CAMARGO DE MORAES, a Pagarema título de indenização por danos morais, consoante fundamentação acima discorrida, 
o montante de R$ 1.500,00 (um mil e quinhentos reais), corrigidos monetariamente pelo INPC desde a data 
desta decisão, acrescidos de juros de 1% ao mês, a partir da citação; condeno ainda, à restituição do valor 
pago pelo demandante como sinal da entrada do imóvel, descontando apenas 20% (vinte por cento), referente às 
despesas, devendo incidir juros de 1% (um por cento) ao mês contados da citação e correção monetária pelo INPC a 
partir da sentença. Contudo, data venia, houve omissão e obscuridade na referida decisão, haja vista que a omissão 
se deu pela ausência dos julgamentos das preliminares (Necessidade de Perícia Técnica e a incompetência de 
Juizado Especial) proposta posteriormente em aditamento de contestação (Fls 251 a 254) para impugnar áudios 
juntados pelo embargado, autorizado a ser realizada pela Douta Magistrada em audiência de Conciliação, 
instrução e julgamento de fls 235 e 236, por ausência de intimação anterior para realizar a já tratada 
impugnação aos áudios anexados."""

## Pré-processamento


In [9]:
#limpeza dos dados, remoção de pontuação
embargo = embargo.replace("," , " ").replace("." , " ").replace("(", " ").replace(")", " ").lower().split()

In [10]:
len(embargo)

266

In [11]:
#criação do corpus (lista das palavras, sem repetição)
corpus = set(embargo)

In [12]:
# Comprimento do corpus
corpus_length = len(corpus)
corpus_length

178

In [13]:
embargo

['o',
 'embargante',
 'sofreu',
 'o',
 'ajuizamento',
 'de',
 'ação',
 'de',
 'danos',
 'morais',
 'e',
 'materiais',
 'cujo',
 'objeto',
 'é',
 'o',
 'reaver',
 'os',
 'valores',
 'pagos',
 'pelo',
 'sinal',
 'dado',
 'em',
 'um',
 'contrato',
 'de',
 'compra',
 'e',
 'venda',
 'de',
 'imóvel',
 'no',
 'qual',
 'não',
 'foi',
 'dado',
 'continuidade',
 'em',
 '24',
 'de',
 'fevereiro',
 'de',
 '2012',
 'o',
 'magistrado',
 'proferiu',
 'decisão',
 'de',
 'fls',
 '277',
 'a',
 '280',
 'que',
 'condenou',
 'todas',
 'as',
 'demandadas',
 'solidariamente',
 'no',
 'seguinte',
 'teor:',
 'diante',
 'de',
 'todo',
 'o',
 'exposto',
 'com',
 'fundamento',
 'no',
 'art',
 '1234',
 'i',
 'do',
 'cpc/2015',
 'julgo',
 'procedentes',
 'em',
 'parte',
 'os',
 'pedidos',
 'constantes',
 'na',
 'inicial',
 'condenando',
 'solidariamente',
 'as',
 'demandadas',
 'xpto',
 'ltda',
 'bob',
 'camargo',
 'de',
 'moraes',
 'a',
 'pagarema',
 'título',
 'de',
 'indenização',
 'por',
 'danos',
 'morais',
 

In [14]:
#Dicionarios para o TF-IDF
dic_palavras = {}
dic_inverso_palavras = {}


In [15]:
#loop pelo corpus para criar os dicionários
for i, palavra in enumerate(corpus):
    dic_palavras[palavra] = i
    dic_inverso_palavras[i] = palavra

In [16]:
dic_inverso_palavras

{0: 'anexados',
 1: 'para',
 2: 'ausência',
 3: 'se',
 4: 'citação',
 5: 'embargado',
 6: 'solidariamente',
 7: 'condeno',
 8: 'decisão',
 9: 'referida',
 10: 'danos',
 11: '251',
 12: 'mil',
 13: 'magistrado',
 14: 'diante',
 15: 'todo',
 16: 'r$',
 17: 'compra',
 18: 'não',
 19: 'magistrada',
 20: 'demandadas',
 21: 'reais',
 22: 'materiais',
 23: 'instrução',
 24: 'os',
 25: 'ser',
 26: 'das',
 27: 'impugnação',
 28: 'embargante',
 29: 'aos',
 30: 'data',
 31: 'demandante',
 32: 'título',
 33: '24',
 34: 'ltda',
 35: 'inicial',
 36: 'valores',
 37: 'monetária',
 38: 'partir',
 39: 'devendo',
 40: 'constantes',
 41: 'mês',
 42: 'dos',
 43: 'anterior',
 44: 'julgo',
 45: 'especial',
 46: 'pago',
 47: 'necessidade',
 48: 'um',
 49: 'já',
 50: 'obscuridade',
 51: 'juntados',
 52: 'objeto',
 53: 'douta',
 54: 'deu',
 55: 'pela',
 56: 'imóvel',
 57: 'discorrida',
 58: 'continuidade',
 59: 'descontando',
 60: 'técnica',
 61: 'venia',
 62: 'dado',
 63: 'às',
 64: 'foi',
 65: 'condenando',
 

In [17]:
#Extração de palavras e sentenças, do texto
dados = []

for x in range(2, len(embargo) -2):
    sentenca = [embargo[x - 2], embargo[x - 1], embargo[x + 1], embargo[x + 2]]
    target = embargo[x]
    dados.append((sentenca, target))

In [18]:
dados

[(['o', 'embargante', 'o', 'ajuizamento'], 'sofreu'),
 (['embargante', 'sofreu', 'ajuizamento', 'de'], 'o'),
 (['sofreu', 'o', 'de', 'ação'], 'ajuizamento'),
 (['o', 'ajuizamento', 'ação', 'de'], 'de'),
 (['ajuizamento', 'de', 'de', 'danos'], 'ação'),
 (['de', 'ação', 'danos', 'morais'], 'de'),
 (['ação', 'de', 'morais', 'e'], 'danos'),
 (['de', 'danos', 'e', 'materiais'], 'morais'),
 (['danos', 'morais', 'materiais', 'cujo'], 'e'),
 (['morais', 'e', 'cujo', 'objeto'], 'materiais'),
 (['e', 'materiais', 'objeto', 'é'], 'cujo'),
 (['materiais', 'cujo', 'é', 'o'], 'objeto'),
 (['cujo', 'objeto', 'o', 'reaver'], 'é'),
 (['objeto', 'é', 'reaver', 'os'], 'o'),
 (['é', 'o', 'os', 'valores'], 'reaver'),
 (['o', 'reaver', 'valores', 'pagos'], 'os'),
 (['reaver', 'os', 'pagos', 'pelo'], 'valores'),
 (['os', 'valores', 'pelo', 'sinal'], 'pagos'),
 (['valores', 'pagos', 'sinal', 'dado'], 'pelo'),
 (['pagos', 'pelo', 'dado', 'em'], 'sinal'),
 (['pelo', 'sinal', 'em', 'um'], 'dado'),
 (['sinal', 'd

In [19]:
#Definir o tamanho de cada embedding
#definido valor 5, pois a sentenca possui 5 itens em cada linha, 
# 2 palavras antes do target, duas palavras depois do target, e o target
embedding_length = 5 

In [20]:
#Classe para o modelo preditivo, usando o CBoW

class CBoW(torch.nn.Module):
    
    #Construtor da classe
    def __init__(self, corpus_length, embedding_dim):
        super(CBoW, self).__init__()
        
        #Camada de entrada do modelo para criação de embedding
        self.embeddings = nn.Embedding(corpus_length, embedding_dim)
        
        #Camadas lineares
        self.linear1 = nn.Linear(embedding_dim, 64)
        self.linear2 = nn.Linear(64, corpus_length)
        
        #Camadas de ativação
        self.activation_function1 = nn.ReLU()
        self.activation_function2 = nn.LogSoftmax(dim = -1)
        
        
    #Passo (forward)
    def forward(self, inputs):
        #Aqui definimos a ordem das camadas da rede neural
        embeds = sum(self.embeddings(inputs)).view(1, -1)
        out = self.linear1(embeds)
        out = self.activation_function1(out)
        out = self.linear2(out)
        out = self.activation_function2(out)
        return out
    
    #Obtém a word_embedding
    def get_word_embedding(self, word):
        word = torch.LongTensor([dic_palavras[word]])
        return self.embeddings(word).view(1, -1)


In [21]:
#Cria o modelo CBoW
modelo = CBoW(corpus_length, embedding_length)

In [22]:
#Função de custo, para calcular o erro
loss_function = nn.NLLLoss()

In [23]:
#Otimizador do modelo (backpropagation)
#lr = learning rate, taxa de aprendizado. quanto menor, mais preciso, porém afeta mais a perfomance. 
# Valor 1 o modelo é mais rápido, mas pode errar mais
optimizer = torch.optim.SGD(modelo.parameters(), lr = 0.01) 

In [24]:
#Função que cria o vetor de setenças, necessário para treinar o modelo

def make_sentence_vector(sentence, word_dict):
    idxs = [word_dict[w] for w in sentence]
    return torch.tensor(idxs, dtype = torch.long)

In [25]:
#o dicionário de palavras será convertido em um vetor de setenças, exemplo:
print(make_sentence_vector(['pela', 'ausência', 'dos', 'julgamentos'], dic_palavras))

tensor([ 55,   2,  42, 109])


## Treinamento do modelo

In [26]:
#Loop por 150 passadas (epochs) de treinamento
for epoch in range(150):
    #Inicia o erro da época com 0
    epoch_loss = 0
    
    #loop pelos dados de entrada (sentença) e saída (target)
    for sentence, target in dados:
        
        #inicializa os gradientes com zero
        modelo.zero_grad()
        
        #cria o vetor de sentença com os dados de entrada (que devem estar no dicionario de palavras)
        sentence_vector = make_sentence_vector(sentence, dic_palavras)
                
        #usa o vetor para fazer previsoes com o modelo e retorna as probabilidades
        log_probs= modelo(sentence_vector)
        
        #calcula o erro do modelo
        loss = loss_function(log_probs, torch.tensor([dic_palavras[target]], dtype=torch.long))
        
        #chama o método de backpropagation para calcular o gradiente da derivada
        loss.backward()
        
        #Otimiza os pesos do modelo e segue para a proxima passada
        #É aqui que o aprendizado acontece
        optimizer.step()
        
        #Atualiza o erro da época
        epoch_loss += loss.data
        
        #Imprime epoch e o erro da época
        print(f"Epoch: {epoch}, Erro do modelo {epoch_loss.item()}")
        

Epoch: 0, Erro do modelo 4.977553844451904
Epoch: 0, Erro do modelo 10.011981964111328
Epoch: 0, Erro do modelo 16.024547576904297
Epoch: 0, Erro do modelo 21.53616714477539
Epoch: 0, Erro do modelo 26.70068359375
Epoch: 0, Erro do modelo 31.7604923248291
Epoch: 0, Erro do modelo 37.2287712097168
Epoch: 0, Erro do modelo 42.97984313964844
Epoch: 0, Erro do modelo 48.68949890136719
Epoch: 0, Erro do modelo 53.29781723022461
Epoch: 0, Erro do modelo 59.194095611572266
Epoch: 0, Erro do modelo 64.07611846923828
Epoch: 0, Erro do modelo 69.003173828125
Epoch: 0, Erro do modelo 73.85546112060547
Epoch: 0, Erro do modelo 78.44146728515625
Epoch: 0, Erro do modelo 83.39527130126953
Epoch: 0, Erro do modelo 88.45968627929688
Epoch: 0, Erro do modelo 94.39999389648438
Epoch: 0, Erro do modelo 99.70362091064453
Epoch: 0, Erro do modelo 104.60704803466797
Epoch: 0, Erro do modelo 111.18357849121094
Epoch: 0, Erro do modelo 116.47061920166016
Epoch: 0, Erro do modelo 122.03123474121094
Epoch: 0, E

In [27]:
#Função para obter uma previsão
def get_resultado_previsto(input, dic_inverso_palavras):
    index = np.argmax(input)
    return dic_inverso_palavras[index]


In [61]:
#função para sentenças (aplicamos aos novos dados o mesmo tratamento usado nos treinos de dados)
def preve_sentenca(sentence):
    #divimos a sentença com split
    sentence_split = sentence.replace("," , " ").replace(".", " ").lower().split()
    
    #criamos o vetor de sentenca
    sentence_vector = make_sentence_vector(sentence_split, dic_palavras)
    
    #faz a previsão com o modelo
    prediction_array = modelo(sentence_vector).data.numpy()
    
    #Print dos resultados
    print(f"Palavras anteriores: {sentence_split[:2]}\n")
    print(f"Palavra prevista: {get_resultado_previsto(prediction_array[0], dic_inverso_palavras)}\n")
    print(f"Palavras seguintes: {sentence_split[2:]}")
    

In [62]:
#previsão com o modelo
preve_sentenca("ausência de anterior para")

Palavras anteriores: ['ausência', 'de']

Palavra prevista: intimação

Palavras seguintes: ['anterior', 'para']


In [63]:
#embedding da palavra
print(modelo.get_word_embedding("intimação"))

tensor([[0.1209, 0.3156, 1.5690, 0.7070, 0.2740]], grad_fn=<ViewBackward0>)


In [57]:
print(preve_sentenca("contados da e correção"))

Palavras anteriores: ['contados', 'da']

Palavra prevista: citação

Palavras seguintes: ['e', 'correção']
None


In [64]:
frase = "e correção monetária pelo INPC"
frase_split = frase.split()
frase = ' '.join(frase_split[0:2])
frase += ' '
frase += ' '.join(frase_split[-2:len(frase_split)])
frase
print(preve_sentenca(frase))
print(f"Palavra esperada: {frase_split[2]}")

Palavras anteriores: ['e', 'correção']

Palavra prevista: monetária

Palavras seguintes: ['pelo', 'inpc']
None
Palavra esperada: monetária
